## Assignment Numpy

#### Consider the below code to answer further questions:
```python
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
```

#### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.
Yes, there is a difference in the data type of variables list_ and array_list. The data type of list_ is list and the data type of array_list is numpy.ndarray. Below is the code to print the data types of both the variables:

In [1]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


#### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [2]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("list_")
for i in list_:
    print(i, type(i))

print("array_list")
for i in array_list:
    print(i, type(i))

list_
1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>
array_list
1 <class 'numpy.str_'>
2 <class 'numpy.str_'>
3 <class 'numpy.str_'>
4 <class 'numpy.str_'>
5 <class 'numpy.str_'>


#### Q3. Considering the following changes in the variable, array_list:
```python
array_list = np.array(object = list_, dtype = int)
```
#### Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and array_list.
Yes, there will be a difference in the data type of the elements present in both the variables, list_ and array_list. The data type of elements present in list_ is str and the data type of elements present in array_list is int. Below is the code to print the data types of each and every element present in both the variables, list_ and array_list:

In [3]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

array_list = np.array(object=list_, dtype=int)

print("list_")
for i in list_:
    print(i, type(i))

print("array_list")
for i in array_list:
    print(i, type(i))

list_
1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>
array_list
1 <class 'numpy.int32'>
2 <class 'numpy.int32'>
3 <class 'numpy.int32'>
4 <class 'numpy.int32'>
5 <class 'numpy.int32'>


#### Consider the below code to answer further questions:
```python
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
```

### Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [5]:
import numpy as np
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

print("Shape: ", num_array.shape)

print("Size: ", num_array.size)

Shape:  (2, 3)
Size:  6


#### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function. [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [6]:
import numpy as np
array = np.zeros((3, 3))
print(array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Q6. Create an identity matrix of shape (5,5) using numpy functions? [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [13]:
import numpy as np
array = np.eye(5, 5, k=0)
print(array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
